version: '3'

services:
  elasticsearch:
    container_name: bruno-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    restart: on-failure
    ports: 
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node

#docker-compose.exe -f .\bruno-elasticsearch-compose.yml up -d
