version: '3'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.19
    restart: on-failure
    ports: 
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - elastic
  
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.19
    restart: on-failure
    ports: 
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elastic


networks:
  elastic:
    external: true