version: '3'

services:

  log-generator:
    container_name: log-generator
    image: airtrack1234/log-generator
    volumes:
      - ${MOUNT_PATH}/${LOG_GENERATOR_LOG_PATH}:/server/log-generator
    networks:
      - elastic

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.19
    restart: on-failure
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.19
    restart: on-failure
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elastic

  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.17.19
    hostname: filebeat
    user: root
    volumes:
      - ${FILEBEAT_CONFIG_PATH}/filebeat.yml:/usr/share/filebeat/filebeat.yml:r
      - ${FILEBEAT_DATA_PATH}:/usr/share/filebeat/data/
      - ${MOUNT_PATH}/${LOG_GENERATOR_LOG_PATH}:/logs/host/
    restart: always
    networks:
      - elastic
    depends_on:
      - elasticsearch
      - kibana


networks:
  elastic:
    external: true