filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/host/server-log*

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
#  index: "filebeat-loggen-%{[agent.version]}-%{+yyyy.MM.dd}"

#setup.kibana.host: '${KIBANA_HOSTS:kibana:5601}'

