version: '3'

services:

  prometheus:
    container_name: prometheus
#    build:
#      context: .
#      dockerfile: Dockerfile_prom
    image: prom/prometheus
    restart: on-failure
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ${PROM_PATH}:/etc/prometheus
    ports:
      - 9090:9090
    networks:
      monitoring-network:
        ipv4_address: 172.30.0.10

  pushgateway:
    container_name: pushgateway
    image: prom/pushgateway
    restart: on-failure
    environment:
      - TZ=Asia/Seoul   # 어짜피 안먹음
    ports:
      - 9091:9091
    networks:
      monitoring-network:
        ipv4_address: 172.30.0.15

volumes: 
  prometheus_home:
    external: true

networks:
  monitoring-network:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1


# START : docker-compose -f docker-compose_monitoring.yml up -d
# STOP : docker-compose -f .\docker-compose_monitoring.yml down