version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins_ansible_network

  ansible:
    image: brunosong-ansible
    container_name: ansible
    volumes:
      - ./ansible:/ansible  # 공유 볼륨 설정
    working_dir: /ansible
    networks:
      - jenkins_ansible_network
    command: "tail -f /dev/null"

networks:
  jenkins_ansible_network:
    driver: bridge

volumes:
  jenkins_home: